### ISSUE TITLE
memcached is not started

### ISSUE THREAD

**Issue by stephdl** [Frederick888/docker-archlinux-sogo#1]
I use your container because I am trying to make a module for NethServer 8 to SOGo, just fine for what I need but I saw that memcached was not started and in logs I saw that many keys were not cached

I relaxed the error by adding in podman systemd service 

`ExecStartPost=/usr/bin/podman exec sogo-app /usr/bin/memcached -d -u sogo`

I figure that maybe there is something missing in the container to make memcached workable after the container boot

**Comment by Frederick888** [comment]
I never intended to start a memcached. It's only installed as it's a dependency of https://aur.archlinux.org/packages/sogo. (It probably should've been an optional dependency.)

**Comment by stephdl** [comment]
yes we use it to cache the keys and fast the sogo : `    SOGoMemcachedHost = "127.0.0.1"; `

it is a common cache memory for SOGo that you provide with your container

**Comment by stephdl** [comment]
no stress nor args from me, I just want to add some details, it seems the documentation expects it [running](https://www.sogo.nu/files/docs/SOGoInstallationGuide.html#_starting_services)

and you are right it is a SOGo [dependency](https://www.sogo.nu/files/docs/SOGoInstallationGuide.html#_software_installation)

we can see even if the directives is not set, SOGo has default options

```
Parameter used to set the hostname and optionally the port of the memcached server.

A path can also be used if the server must be reached via a Unix socket.

Defaults to localhost.
```

BTW, you did a nice job for  this container :D
